package com.zeebe.entity;

public class SysInstance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.instanceId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private Integer instanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.instanceName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private String instanceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.modelName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.processId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.instanceParams
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private String instanceParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_instance.status
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.instanceId
     *
     * @return the value of sys_instance.instanceId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public Integer getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.instanceId
     *
     * @param instanceId the value for sys_instance.instanceId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setInstanceId(Integer instanceId) {
        this.instanceId = instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.instanceName
     *
     * @return the value of sys_instance.instanceName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.instanceName
     *
     * @param instanceName the value for sys_instance.instanceName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.modelName
     *
     * @return the value of sys_instance.modelName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.modelName
     *
     * @param modelName the value for sys_instance.modelName
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.processId
     *
     * @return the value of sys_instance.processId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.processId
     *
     * @param processId the value for sys_instance.processId
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.instanceParams
     *
     * @return the value of sys_instance.instanceParams
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public String getInstanceParams() {
        return instanceParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.instanceParams
     *
     * @param instanceParams the value for sys_instance.instanceParams
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setInstanceParams(String instanceParams) {
        this.instanceParams = instanceParams == null ? null : instanceParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_instance.status
     *
     * @return the value of sys_instance.status
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_instance.status
     *
     * @param status the value for sys_instance.status
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}