package com.zeebe.entity;

import java.util.Date;

public class SysModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.modelId
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.modelName
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.modelLocation
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private String modelLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.createTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.updateTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.status
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_model.remark
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.modelId
     *
     * @return the value of sys_model.modelId
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.modelId
     *
     * @param modelId the value for sys_model.modelId
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.modelName
     *
     * @return the value of sys_model.modelName
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.modelName
     *
     * @param modelName the value for sys_model.modelName
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.modelLocation
     *
     * @return the value of sys_model.modelLocation
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public String getModelLocation() {
        return modelLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.modelLocation
     *
     * @param modelLocation the value for sys_model.modelLocation
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setModelLocation(String modelLocation) {
        this.modelLocation = modelLocation == null ? null : modelLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.createTime
     *
     * @return the value of sys_model.createTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.createTime
     *
     * @param createTime the value for sys_model.createTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.updateTime
     *
     * @return the value of sys_model.updateTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.updateTime
     *
     * @param updateTime the value for sys_model.updateTime
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.status
     *
     * @return the value of sys_model.status
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.status
     *
     * @param status the value for sys_model.status
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_model.remark
     *
     * @return the value of sys_model.remark
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_model.remark
     *
     * @param remark the value for sys_model.remark
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}