package com.zeebe.entity;

public class SysMicroservice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.microserviceId
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private Integer microserviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.microserviceName
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private String microserviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.microserviceLocation
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private String microserviceLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.params
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.description
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_microservice.status
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.microserviceId
     *
     * @return the value of sys_microservice.microserviceId
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public Integer getMicroserviceId() {
        return microserviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.microserviceId
     *
     * @param microserviceId the value for sys_microservice.microserviceId
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setMicroserviceId(Integer microserviceId) {
        this.microserviceId = microserviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.microserviceName
     *
     * @return the value of sys_microservice.microserviceName
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public String getMicroserviceName() {
        return microserviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.microserviceName
     *
     * @param microserviceName the value for sys_microservice.microserviceName
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setMicroserviceName(String microserviceName) {
        this.microserviceName = microserviceName == null ? null : microserviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.microserviceLocation
     *
     * @return the value of sys_microservice.microserviceLocation
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public String getMicroserviceLocation() {
        return microserviceLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.microserviceLocation
     *
     * @param microserviceLocation the value for sys_microservice.microserviceLocation
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setMicroserviceLocation(String microserviceLocation) {
        this.microserviceLocation = microserviceLocation == null ? null : microserviceLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.params
     *
     * @return the value of sys_microservice.params
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.params
     *
     * @param params the value for sys_microservice.params
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.description
     *
     * @return the value of sys_microservice.description
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.description
     *
     * @param description the value for sys_microservice.description
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_microservice.status
     *
     * @return the value of sys_microservice.status
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_microservice.status
     *
     * @param status the value for sys_microservice.status
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}