package com.zeebe.mapper;

import com.zeebe.entity.SysInstance;
import java.util.List;

public interface SysInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_instance
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    int insert(SysInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_instance
     *
     * @mbg.generated Sun Oct 06 11:32:13 CST 2019
     */
    List<SysInstance> selectAll();

    SysInstance findInstanceByInstanceName(String instanceName);

    int updateByInstanceId(SysInstance record);
}