package com.zeebe.mapper;

import com.zeebe.entity.SysModel;
import java.util.List;

public interface SysModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    int insert(SysModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Tue Sep 24 16:54:12 CST 2019
     */
    List<SysModel> selectAll();

    SysModel findModelLoationByModelName(String modelName);
}