package com.zeebe.mapper;

import com.zeebe.entity.SysMicroservice;
import java.util.List;

public interface SysMicroserviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_microservice
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    int insert(SysMicroservice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_microservice
     *
     * @mbg.generated Wed Sep 25 10:22:57 CST 2019
     */
    List<SysMicroservice> selectAll();

    int deleteByMicroserviceId(Integer microserviceId);

    int updateByMicroserviceId(SysMicroservice record);

    String findMicroserviceLocationByMicroserviceName(String microserviceName);

    SysMicroservice selectMicroserviceByMicroserviceName(String microserviceName);
}